services:
  app1:
    build:
      context: ./app1
      dockerfile: Dockerfile
    environment:
      - STORAGE_URL=http://app2
    ports:
      - "8000:8000"

  app2:
    build:
      context: ./app2
      dockerfile: Dockerfile
    volumes:
      - ./app2/flag.txt:/flag.txt:ro
    environment:
      - XDEBUG_MODE=debug
      - XDEBUG_CONFIG=client_host=host.docker.internal client_port=9003
    extra_hosts:
      - "host.docker.internal:host-gateway"
