http:
  routers:
    gateway-router:
      rule: "PathPrefix(`/`)"
      service: gateway-service
      priority: 100
      entryPoints: ["websecure"]
      tls: {}

  services:
    gateway-service:
      loadBalancer:
        servers:
          - url: "http://gateway:8000"
        passHostHeader: true
